# Adapted from version in george repo by Dan Foreman-Mackey

sudo: false
language: generic
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

env:
    global:
        - TEST_LANG='python'

matrix:
    include:

        # Linux
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12

        # OSX
        - os: osx
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12
        - os: osx
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.12

install:
    - source .ci/travis.sh

after success:
    - codecov