language: python
python:
  - 2.7
script:
  - df -kh .
  - export PATH="$PWD/miniconda/bin:$PATH"
  - source setup/setup.sh
  - conda install scikit-learn
  - pip install george
  - export PYTHONPATH="$PWD/code/:$PYTHONPATH"
  - cd tests
  - nosetests